matrix:
  include:
  - os: osx
    osx_image: xcode12.5
    env:
    - OSX_TARGET_ARCHITECTURE: arm64
    - OSX_TARGET_NAME: cimgui.arm64.dylib
  - os: osx
    osx_image: xcode9.4
    env:
    - OSX_TARGET_ARCHITECTURE: x86_64
    - OSX_TARGET_NAME: cimgui.dylib
language: cpp
script:
- "./ci-build.sh"
deploy:
  provider: releases
  api_key:
  file_glob: true
  file: cimgui/build/Release/*.dylib
  on:
    tags: true
    repo: mellinoe/ImGui.NET-nativebuild
notifications:
  email: false
